---
title: "README"
author: "Jono Tuke"
date: "14/03/2019"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 18th March 2019
  
- Copy Paper ID to all rows involving that paper.
- Copy Condition to all relevant rows. 
- Create a new column containing "Continuous", "Quartile" etc.
- Delete blank rows within a paper, currently left blank rows separating papers to make it easier to read
- Highlighted any obviously dubious cells/entries in Red, left yellow ones from Stephen for clarification
- Tidied up "minus" entries - Note that the Confidence Interval notation is not standardised! 
- Explicitly annotated "plus" with the prior categories
- Removed "adj" from conditions, where the covariates indicate a deeper analysis
- Inserted annotations, such as "- male", into the "Condition" description to uniquely identify each test. 
  

# Thursday 16 May 2019

Meeting NB and JT. 

- Check that mapper uses regex
- pv -> three columns - pv, ci, counts, boolean for less than

# Monday 20 May 2019

Email from Nigel

> Hi Jono,
>
> I hope you are enjoying EuroVision, because I am sure you didn’t enjoy the election coverage last night!
>
> I have uploaded a new version of the data with a new column under T3 indicating whether it used Free T3 or Total T3 - the former being more valid as Total T3 is contaminated (I think by T4, but you probably know). By adding this colunm, we can check if Free T3 is also a good proxy (like T4) or if it only works as well because of the  Total T3 investigations.
>
> I also forgot to mention that Stephen doesn’t want any “endocrine” system, but instead for BP, insulin and diabetes to be listed under metabolism. There should be no Thyroid in the condition list, and so we reworded a number of the conditions.
>
> Just to record it: we should treat all Y* and N* as Y and N, respectively. They have been inferred, but highly reliably.
>
> Finally, there is one "Cox PH*” because Stephen wasn’t completely sure whether it was Cox PH. When we looked at it, I discovered it was really a test for “trend” across 3 tertiles. I doubt that is Cox PH, but they didn’t say anything in their methods that was relevant. What method would you use? There are few of these “trend” analyses, so there might some further changes in this column, but for now that is not important.
>
> All the best,
>
> Nigel.


# Monday 27 May 2019

1. Clean up folder structure: 
    1. added dates to file names
    2. move info about changes and conversations to `correspondence` folder. 
2. [x] Work through NB's cleaning notes and adjust accordingly. 
3. [x] Work through NB's email of 20 May and adjust accordingly. 

# Thursday 30 May 2019

1. Finished adding new clean pv function and cleaned the rest of the data. 
2. Primary analysis using RE model. 

# Friday 31 May 2019

1. Meeting with NB - happy with results, but going to add a cohort within paper RI. 

# Saturday 01 Jun 2019

Realised that making mistake - using ID - test inside paper - rather than paper as RI. Changed - results more robust but no changes - phew. 

1. Code to get cohorts. 

# Sunday 02 Jun 2019

1. code to look at cohort / paper RI. All done. 

# Tuesday 04 Jun 2019

1. [] Add in style (quantiles etc) as either RI or split data based on. 
2. [x] Add in level of sophistication of model either as RI or split data based on.
3. [x] ANCOVA for probability of significance against n_obs, n_cov for each Tx, expect that slope of T3 is not zero. Realised that already done with `get_cov()` function. 
4. [x] Add in extra treatment for Free T3 versus Total T3
5. [x] Aggregate systems according to "atrial fibrillation (AF)[26-30], osteoporosis [31-35], and  cancer" (high tyroid function) and "steatohepatitis [39-41] and the features of the metabolic syndrome" (low thyroid function)
6. [] Repeat overall test with minimum (and maximum) sophistication per paper

# Tuesday 11 Jun 2019

Email from Stephen

> Dear All,
> 
> Find attached a draft paper. This has been prepared pending final mathematical analyses on the understanding that the results will not change. I have edited a little and have deleted many figures and tables, replacing them with a sentence or two. I have anticipated that our excel sheet with all of the data will be submitted as a supplement. I also imagine that we will submit some of the graphs of the results. I have yet to tidy up references.
> 
> Dear Nigel,
please check that you are happy with the logic etc and would be happy to have the paper submitted in your absence once the gaps are filled. You Jono and I might need to meet before you leave.
> 
> Dear Henrik,
please check the paper- in particular note that the literature search is now in 2 stages-ie a general review and then focus on the articles that are most relevant. We do not as yet have a figure to describe the searches(?). Note that I have indicated in the text that our study is not an interventional study and that this is the reason for the adjustment of the NOS scale.(?)
>
> Dear Simon and Nigel,
> I think I am still awaiting your consideration of the effects of multiple comparisons. We will also need to be able to say something about whether the use of T3 in some studies and FT3 in others is important. Are you able to confirm that parameters associated with hyperthyroidism (AF, low bone density and cancer) were more consistent in terms of correlations than parameters assoc c low thyroid function (obesity/metabolic syndrome/steatohepatitis). e.g. Was 'no significant relationship ' more likely with low thyroid function parameters.
>
> Are you able to comment on whether or not measurement of T3/FT3 adds anything to the measurement of FT4?

> Note that 'Statistical methods' and 'Results' need filling out/re-casting depending on the details of what you did and found. Please also suggest best graphs to include.

> Dear All,
'Thyroid' requires all figures to be in .tif or .eps files. These are not available on my old program. Are tables too, saveable in such format- do they need to be- are they counted as 'figures'? Henrik , if you do figure(s) for the search can you do the appropriate format?
best wishes,
Stephen

# Sunday 04 Aug 2019

## Instructions for figures

Please follow these instructions when preparing figure files for uploading.

- Line illustrations must be submitted at 900 dpi.
- Halftones and color photos should be submitted at a minimum of 300 dpi.
- Power Point files cannot be uploaded.
- Save art as either TIFF or EPS files. Avoid submitting JPEG or PDF files.
- Color art must be saved as CMYK, not RGB.
- Color illustrations can be printed in the journal, with a subsidy from the author(s).

If you need directions on how to convert a Power Point slide to acceptable format, go to <www.liebertpub.com/MEDIA/pdf/ppconvert.pdf>

# Monday 30 Sep 2019

Reviewer comments

2)      The authors should tabulate the detailed correlation data from each study and report this in the manuscript.  This would include the correlation estimates with 95% confidence intervals (if available), type of statistical test, and statistical significance, as well as sample size if different from that presented in Table 1.
3)      A conventional weighted technique should be used for the meta-analyses (some examples of established techniques include those reported by Hedges and Olkin, 1985 or Schmidt and Hunter, 1990).  Statistical heterogeneity of the meta-analyses should be reported.  The description of the number studies reporting a statistically significant result and logistic regression model presented in the manuscript are interesting and can be retained, but do not really replace that of a traditional weighted statistic.

# Wednesday 13 Nov 2019

Meeting with NB

1. Reclean the data
2. New column - gives hypo / hyper / both / ind so 4 levels
3. New column pregnancy -> new system; most are about the baby - 1 (Knight) is about the mother - can we treat this as both metabolic and pregnancy?
4. New column NOS score - measure of paper quality
5. TSH incong - fill down - multiple levels - may be too stratified. 
6. Cross-section not sure but may be if time is involved. but not in a prospective / retrospective sense. 
7. May ditch Total T3. 
8. Meta-analysis - idea is to stratify on system / model, then if sufficient info - randomly sample on result for analysis. 
9. Key arguments against vote couting:
    a. Matched pairs within each paper comparing FT4 and TSH
    b. RE modelling to account for standard causes of heterogenecity. 
    
  
